apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: books-web-ingress
spec:
  podSelector:
    matchLabels:
      app: books-web
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: cloudflared
      ports:
        - port: 5001
          protocol: TCP
